vich_uploader:
    db_driver: orm

    mappings:
        smartphones:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images/smartphones'
            namer: Vich\UploaderBundle\Naming\UniqidNamer







